# Deliverable 1. Retrieve Weather Data.
---
1. Create a folder called `Weather_Database` to save all the files related with this deliverable.

2. Save the `Weather_Database_starter_code.ipynb` starter code to the `Weather_Database` folder and rename it as `Weather_Database.ipynb`.

3. Use the `np.random.uniform` function to generate a new set of 2,000 random latitudes and 2,000 longitudes.

4. Use the `citipy` module to get the nearest city for each latitude and longitude combination.

5. Import your OpenWeatherMap's API key and assemble the API call URL as a string variable. Recall to edit the `config.py` file to add your API key; also, it's critical to avoid publishing your API key on your GitHub repository.

6. Retrieve the following information from the API call:

    * Latitude and longitude

    * Maximum temperature

    * Percent humidity

    * Percent cloudiness

    * Wind speed

    * Weather description (for example, clouds, fog, light rain, clear sky)

7. Add the weather data to a new DataFrame.

8. Export the DataFrame as a CSV file, and save it as `WeatherPy_Database.csv` in the `Weather_Database` folder.
---

In [23]:
# Import initial libraries
import numpy as np
import pandas as pd
from citipy import citipy

## Use the `np.random.uniform` function to generate a new set of 2,000 random latitudes and 2,000 longitudes.

In [24]:
# Create a set of random latitude and longitude combinations
lats = np.random.uniform(-90, 90, 2000)
lngs = np.random.uniform(-180, 180, 2000)

# Use the zip function to create an iterator of tuples containing the latitude and longitude combinations
lat_lngs = zip(lats, lngs)

In [25]:
# Add the latitudes and longitudes to a list
coordinates = list(lat_lngs)

## Use the `citipy` module to get the nearest city for each latitude and longitude combination.

In [26]:
# Create an empty list for holding the cities
cities = []

# Use a for loop to identify nearest city for each latitude and longitude combination using the citipy module
for coordinate in coordinates:
    # Use the citipy module to identify the nearest city to the current coordinate
    city = citipy.nearest_city(coordinate[0], coordinate[1])
    
    # If the city is unique, then add it to a our cities list
    if city.city_name not in cities:
        cities.append(city.city_name)

# Print the city count to confirm sufficient count
print(len(cities))

757

## Import your OpenWeatherMap's API key and assemble the API call URL as a string variable. Recall to edit the `config.py` file to add your API key.

In [ ]:
# Import the requests library
import requests

# Import the time library
import time

# Import the datetime module from the datetime library
from datetime import datetime

# Import the OpenWeatherMap's API key
from config import weather_api_key

In [ ]:
# Assemble the OpenWeatherMap's API call
# The sample output appears to use imperial units, so this is used here.
url = 'https://api.openweathermap.org/data/2.5/weather?units=imperial&appid=' + weather_api_key

## Retrieve the following information from the API call.

- The latitude and longitude
- The Max temperature
- The % humidity
- The % cloudiness
- The Wind speed
- The Weather description, i.e., cloudy, fog, light rain, clear sky, etc.

In [ ]:
# Create an empty list to hold weather data for each city
city_data = []

# Print a message to indicate that the data retrieval starts
print("Beginning Data Retrieval     ")
print("-----------------------------")

# Create counters and set them to 1
record_count = 1
set_count = 1

# Loop through all the cities in our list to fetch weather data for each city
for i, city in enumerate(cities):
        
    # Group cities in sets of 50 for logging purposes
    if (i % 50 == 0 and i >= 50):
        set_count += 1
        record_count = 1
        time.sleep(60)

    # Create an endpoint URL for each city
    city_url = url + "&q=" + city.replace(" ","+")
    
    # Log the url, record, and set numbers
    print(f"Processing Record {record_count} of Set {set_count} | {city}")

    # Add 1 to the record count
    record_count += 1

    # Run an API request for each of the cities
    try:
        city_weather = requests.get(city_url).json()
        # Parse out the latitude, longitude, max temp, humidity, cloudiness, wind, country, and weather description
        # lon, lat dict ('coord') will start the data dictionary, and the rest of the items will be appended
        data_dict = city_weather['coord']
        data_dict['Max Temp'] = city_weather['main']['temp_max']
        data_dict['Humidity'] = city_weather['main']['humidity']
        data_dict['Cloudiness'] = city_weather['clouds']['all']
        data_dict['Wind Speed'] = city_weather['wind']['speed']
        data_dict['Country'] = city_weather['sys']['country']
        data_dict['Current Description'] = city_weather['weather'][0]['description']
        # Add city name in normal capitalized format
        data_dict['City'] = city.title()


        # Append the city information into the city_data list
        city_data.append(data_dict)
    
    # If an error is experienced, skip the city
    except:
        print("City not found. Skipping...")
        pass

# Indicate that the data retrieval is complete 
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")
print(city_data[0:5])

In [ ]:
# Print the length of the city_data list to verify how many cities you have
len(city_data)

## Add the weather data to a new DataFrame.

In [9]:
# Use the city_data list to create a new pandas DataFrame.
city_data_df = # YOUR CODE HERE

In [10]:
# Display sample data
city_data_df.head(10)

,City,Lat,Lng,Max Temp,Current Description,Humidity,Cloudiness,Wind Speed,Country
0,Bluff,-46.6000,168.3333,56.80,few clouds,68,21,2.28,NZ
1,Metro,-5.1131,105.3067,88.48,overcast clouds,54,92,4.52,ID
2,Pacific Grove,36.6177,-121.9166,64.08,clear sky,87,0,4.61,US
3,Saint George,37.1041,-113.5841,79.95,clear sky,40,0,10.36,US
4,Mataura,-46.1927,168.8643,56.48,few clouds,56,15,2.44,NZ
5,Biltine,14.5333,20.9167,80.42,scattered clouds,61,27,3.36,TD
6,Gao,16.6362,1.6370,85.73,broken clouds,47,77,6.31,ML
7,Hithadhoo,-0.6000,73.0833,82.00,scattered clouds,72,47,7.78,MV
8,Bambous Virieux,-20.3428,57.7575,76.21,broken clouds,78,75,13.80,MU
9,Rikitea,-23.1203,-134.9692,73.35,clear sky,72,3,14.23,PF

In [11]:
# Display the DataFrame's column names using the columns Pandas function
city_data_df.columns

Index(['City', 'Lat', 'Lng', 'Max Temp', 'Current Description', 'Humidity',
       'Cloudiness', 'Wind Speed', 'Country'],
      dtype='object')

In [12]:
# Create a list to reorder the column names as follows:
# "City", "Country", "Lat", "Lng", "Max Temp", "Humidity",  "Cloudiness", "Wind Speed",  "Current Description"
# YOUR CODE HERE

# Recreate the DataFrame by using the new column order
# YOUR CODE HERE

# Display sample data
# YOUR CODE HERE

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,Bluff,NZ,-46.6000,168.3333,56.80,68,21,2.28,few clouds
1,Metro,ID,-5.1131,105.3067,88.48,54,92,4.52,overcast clouds
2,Pacific Grove,US,36.6177,-121.9166,64.08,87,0,4.61,clear sky
3,Saint George,US,37.1041,-113.5841,79.95,40,0,10.36,clear sky
4,Mataura,NZ,-46.1927,168.8643,56.48,56,15,2.44,few clouds
5,Biltine,TD,14.5333,20.9167,80.42,61,27,3.36,scattered clouds
6,Gao,ML,16.6362,1.6370,85.73,47,77,6.31,broken clouds
7,Hithadhoo,MV,-0.6000,73.0833,82.00,72,47,7.78,scattered clouds
8,Bambous Virieux,MU,-20.3428,57.7575,76.21,78,75,13.80,broken clouds
9,Rikitea,PF,-23.1203,-134.9692,73.35,72,3,14.23,clear sky

In [13]:
# Display the data types of each column by using the dtypes Pandas function
# YOUR CODE HERE

City                    object
Country                 object
Lat                    float64
Lng                    float64
Max Temp               float64
Humidity                 int64
Cloudiness               int64
Wind Speed             float64
Current Description     object
dtype: object

## Export the DataFrame as a CSV file, and save it as `WeatherPy_Database.csv` in the `Weather_Database` folder.

In [15]:
# Set the output file name
# YOUR CODE HERE

# Export the city_data DataFrame into a CSV file
# YOUR CODE HERE